config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#all_books'
  get '/all_books', to: 'books#all_books'
  patch '/borrow_book/:id' => 'books#borrow_book'

  resources :books do
    member do
      patch 'borrow'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def all_books
    @books = Book.all
  end

  def borrow
    @book = Book.find(params[:id])
    # if @book.id == nil
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end

  # def correct_user
  #   @book = current_user.books.find_by(id: params[:id])
  #   redirect_to books_path, notice: 'Not authorized to edit this book' if @book.nil?
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :userid)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <br/>
  <div class="field form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control', placeholder: 'Author' %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :book_user_id, class: 'form-control', value: current_user.id, type: 'hidden'%>
  </div>

  <div class="actions">
    <br/>
    <%= form.submit class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/books/all_books.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
  <tr>
    <th>Title</th>
    <th>Author</th>

    <% if current_user.admin? %>
      <th>User Id</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <% if book.user_id == 4 %>
      <tr>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>

        <% if current_user.admin? %>
          <td><%= book.user_id %></td>
        <% end %>

      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? %>
  <%= link_to 'New Book', new_book_path, class: "btn btn-secondary" %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<br>
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if user_signed_in? %>

  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>User Id</th>
    </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>
      <% if book.user == current_user %>
        <tr>
          <td><%= link_to book.title, book %></td>
          <td><%= book.author %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>

  <br>

<% else %>
  <h2>Welcome to the library app!</h2>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<br>
<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @book.title %></h1>
  <p class="lead">Author: <%= @book.author %></p>
  <hr class="my-4">
  <% if current_user.admin? %>
    <%= link_to 'Edit', edit_book_path(@book), class:"btn btn-secondary" %>
    <%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' },
                    class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Borrow', borrow_book_path(@book.id), method: :patch, class: 'btn btn-secondary' %>
  <% end %>
  <br><br>
  <%= link_to 'Back', books_path%>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>Library App</title>
</head>
<body>

  <%= render 'pages/header' %>
  <div class="container">

    <% if notice %>
      <br>
      <%= render 'layouts/alerts' %>
    <% end %>

    <br>
    <%= yield %>
  </div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
-->
</body>
</html>

app/views/pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Library App', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Book Library', all_books_path, class: 'nav-link' %>
        </li>

        <% if user_signed_in? %>

          <% unless current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'My Books', books_path, class: 'nav-link' %>
            </li>
          <% end %>

          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'Add Book', new_book_path, class: 'nav-link' %>
            </li>
          <% end %>

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/pages/index.html.erb
<h1>Main Page</h1>
This is the first main page
It should contain log in stuff